### ndarray: 一种多维数组对象

In [2]:
import numpy as np

data = np.random.randn(2, 3)
data

array([[ 0.80241593,  1.2018086 ,  0.24400635],
       [ 1.0867613 ,  0.46514629, -0.99678333]])

In [4]:
data * 10

array([[ 8.02415931, 12.01808598,  2.44006354],
       [10.86761296,  4.65146291, -9.96783332]])

In [6]:
data + data

array([[ 1.60483186,  2.4036172 ,  0.48801271],
       [ 2.17352259,  0.93029258, -1.99356666]])

### 创建ndarray

In [9]:
data1 = [6, 7.5, 8, 0, 1] # list
arr1 = np.array(data1) # numpy array

In [11]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
print(type(arr1))
print(type(data1))

<class 'numpy.ndarray'>
<class 'list'>


In [19]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
print(arr2.ndim) # dimension 
arr2.shape # shape 2 rows 4 columns

2


(2, 4)

In [24]:
arr1.dtype

dtype('float64')

In [25]:
arr2.dtype

dtype('int64')

In [26]:
np.ones((2, 3, 4)) # 3D array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [30]:
arr3 = np.random.randn(3, 3)
arr3[2].shape
arr3[2, :].shape

(3,)

In [31]:
arr_16 = np.arange(16).reshape((2, 2, 4))

arr_16

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [35]:
arr_16.transpose((1, 0, 2))
arr_16.transpose((0, 2, 1))

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])